# Generated by Django 4.2.4 on 2023-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_rename_categoria_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='file',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
