# Generated by Django 4.2.4 on 2023-08-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(max_length=500),
        ),
    ]
