# Generated by Django 4.2.4 on 2023-08-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_alter_libro_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Autor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
