# Generated by Django 4.2.4 on 2023-08-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preguntaS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=90, null=True)),
                ('Correo', models.EmailField(max_length=50)),
                ('respuesta', models.CharField(max_length=150)),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntaS.pregunta')),
            ],
        ),
    ]
