# Generated by Django 4.2.4 on 2023-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idUser',
            new_name='idRespuesta',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
