# Generated by Django 4.2.4 on 2023-08-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_correo_user_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idRespuesta',
            new_name='IdRespuesta',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='respuesta',
            new_name='Respuesta',
        ),
    ]
