# Generated by Django 4.2.4 on 2023-08-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_correo_user_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Respuesta',
        ),
        migrations.AddField(
            model_name='user',
            name='Answer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
