# Generated by Django 4.2.4 on 2023-08-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0002_rename_categoria_libro'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUser', models.CharField(max_length=30)),
                ('calificacion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=30)),
                ('idTienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
                ('idUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
