# Generated by Django 4.2.4 on 2023-08-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opiniones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='idTienda',
            new_name='idLibro',
        ),
    ]
