# Generated by Django 4.2.4 on 2023-08-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipocategoria', models.CharField(max_length=30)),
                ('resumen', models.CharField(max_length=500)),
            ],
        ),
    ]
